# Generated by Django 3.2.6 on 2024-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('descriere', models.TextField()),
                ('citit', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('imagine', models.ImageField(upload_to='cursuri/imagini/')),
            ],
        ),
    ]
